//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TorneosITM_API.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class AdministradorITM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdministradorITM()
        {
            this.Torneos = new HashSet<Torneo>();
        }
    
        public int idAministradorITM { get; set; }
        public string Documento { get; set; }
        public string NombreCompleto { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]

        public virtual ICollection<Torneo> Torneos { get; set; }
    }
}
